Decode the subprocess output to get pyrasite.inspect working on py3.
Before this fix, the following exception gets thrown on Python 3.3:

TypeError: Type str doesn't support the buffer API